config:
energy:
logbook:
my:
cloud:
media_source:
ssdp:
zeroconf:
usb:
shopping_list:
system_health:
sun:
mobile_app:
http:
  ip_ban_enabled: false
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/16
    - 172.30.33.0/24
    - 172.0.0.0/8
    - 192.168.10.0/24
logger:
  default: info
recorder: !include includes/recorder.yaml
homeassistant:
  country: UA
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  currency: UAH
  time_zone: Europe/Kiev
  customize: !include_dir_merge_named customize
  external_url: !secret external_url
  internal_url: !secret internal_url
  # packages: !include_dir_merge_named includes/packages
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/lovelace-mushroom/mushroom.js
    - /local/community/lovelace-card-mod/card-mod.js
notify: !include includes/notify.yaml
telegram_bot: !include includes/telegram.yaml
history:
light: !include includes/light.yaml
timer: !include includes/timer.yaml
input_boolean: !include includes/input_boolean.yaml
sensor: !include_dir_merge_list includes/sensor
binary_sensor: !include includes/binary_sensors.yaml
switch: !include includes/switch.yaml
automation: !include_dir_merge_list automations
utility_meter: !include includes/utility_meter.yaml
climate: !include includes/climate/climate.yaml
mqtt: !include includes/mqtt_devices.yaml
blueprint:
lovelace:
  mode: yaml
  resources: !include ui_lovelace/resources.yaml
# google_assistant: !include includes/google_assistant.yaml
# google: !include includes/google_calendars.yaml
alarm_control_panel: !include includes/alarm_control_panel.yaml
command_line: !include includes/command_line.yaml
input_button:
input_number:
input_select:
input_datetime: !include includes/input_datetime.yaml
counter:
schedule:
input_text:
bluetooth:
conversation:
tts: !include includes/tts.yaml
stream:
  ll_hls: true
assist_pipeline:
battery_notes:
template: !include includes/template_sensors.yaml
