background: var(--background-image)
preload_cards:
  - custom:mini-graph-card
  - custom:weather-card
  - custom:button-card
# preload_rows:
#   - divider
button_card_templates: !include ui_lovelace/button_card_templates.yaml
swipe_nav:
  swipe_amount: 30
  wrap: true
  animate: swipe
  prevent_default: true
views:
  - !include ui_lovelace/views/home.yaml
  - !include ui_lovelace/views/security.yaml
  - !include ui_lovelace/views/doors.yaml
  - !include ui_lovelace/views/lights.yaml
  - !include ui_lovelace/views/camera.yaml
  - !include ui_lovelace/views/users.yaml
  - !include ui_lovelace/views/energy.yaml
  - !include ui_lovelace/views/net.yaml
  - !include ui_lovelace/views/sensors.yaml
  - !include ui_lovelace/views/weather.yaml
  - !include ui_lovelace/views/floorplan.yaml
  - !include ui_lovelace/views/batteries.yaml
  - !include ui_lovelace/views/control.yaml
