title: security
path: security
type: panel
icon: mdi:shield-check
cards:
  - type: custom:bootstrap-grid-card
    cards:
      - type: row
        cards:
          - type: custom:mushroom-chips-card
            class: col-xs-12
            chips:
              - type: back
              - type: menu
              - type: template
                content: "{{int(states.sensor.opened_doors.state)}}"
                icon: mdi:door-open
              - type: template
                content: "{{int(states.sensor.opened_windows.state)}}"
                icon: mdi:window-open-variant
              - type: weather
                entity: weather.home
                show_conditions: true
                show_temperature: true

