- platform: template
  sensors:
    energy_cost:
      device_class: monetary
      friendly_name: "Monthly Energy Cost"
      unit_of_measurement: "UAH"
      value_template: "{{((states.sensor.monthly_energy_normal.state) | float * 2.64) | round(2)}}"
