- platform: template
  sensors:
    current:
      friendly_name: "Current"
      unit_of_measurement: 'A'
      value_template: "{{ state_attr('sensor.energy_meter_energy', 'current') }}"
      icon_template: mdi:current-ac

- platform: template
  sensors:
    voltage:
      friendly_name: "Voltage"
      unit_of_measurement: 'V'
      value_template: "{{ state_attr('sensor.energy_meter_energy', 'voltage') }}"
      icon_template: mdi:flash-triangle

- platform: template
  sensors:
    power:
      friendly_name: "Power"
      unit_of_measurement: 'W'
      value_template: "{{ state_attr('sensor.energy_meter_energy', 'power') }}"
      icon_template: mdi:file-powerpoint-box