#   Вмикаємо gyverlamp в редмиі "sleepingmode", і врубаємо таймер на годину (gyverlamp_1h_off)
- id: Gyver_on_at_sleepingmode
  alias: Gyver_on_at_sleepingmode
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.virt_sleepingmode
    to: "on"
  action:
    - service: light.turn_on
      data:
        brightness_pct: 10
        effect: Fire 2012
      target:
        entity_id: light.gyver
    # - service: select.select_option
    #   data:
    #     option: Fire 2012 # name of preset
    #   target:
    #     entity_id: select.gyver_preset
    - service: timer.start
      entity_id: timer.gyverlamp_1h_off

#   Вимикаємо gyverlamp після спрацювання таймера на годину
- alias: Gyverlamp_off_1h_timer
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.gyverlamp_1h_off
  condition:
    - condition: state
      entity_id: light.gyver
      state: "on"
  action:
    - service: light.turn_off
      target:
        entity_id: light.gyver
    - service: timer.cancel
      entity_id: timer.gyverlamp_1h_off
