- alias: Gyver Brightness
  trigger:
    platform: state
    entity_id: input_number.brightness
  action:
    - service: mqtt.publish
      data_template:
        topic: homeassistant/light/ESP-74e9c8/brightness/set
        payload_template: "{{ trigger.to_state.state | int }}"
        # payload_template: BRI{{ trigger.to_state.state | int }}
  id: SET_Gyver_Brightness
- alias: Gyver Speed
  trigger:
    platform: state
    entity_id: input_number.speed
  action:
    - service: mqtt.publish
      data_template:
        topic: homeassistant/light/ESP-74e9c8/effect/speed/set
        payload_template: "{{ trigger.to_state.state | int }}"
        # payload_template: SPD{{ trigger.to_state.state | int }}
  id: SET_Gyver_Speed
- alias: Gyver Scale
  trigger:
    platform: state
    entity_id: input_number.scale
  action:
    - service: mqtt.publish
      data_template:
        topic: homeassistant/light/ESP-74e9c8/effect/scale/set
        payload_template: "{{ trigger.to_state.state | int }}"
        # payload_template: SCA{{ trigger.to_state.state | int }}
  id: SET_Gyver_Scale
- alias: Set Gyver Mode
  trigger:
    platform: state
    entity_id: input_select.ledlamp_mode
  action:
    service: mqtt.publish
    data_template:
      topic: homeassistant/light/ESP-74e9c8/effect/set
      payload_template: "{{ states('input_select.ledlamp_mode')}}"
      #payload_template: EFF{{ states.input_select.ledlamp_mode.state }}
  id: Set_Gyver_Mode
#   Вимикаємо gyverlamp після спрацювання таймера на годину
- alias: Gyverlamp_off_1h_timer
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.gyverlamp_1h_off
  condition:
    - condition: state
      entity_id: light.gyver_bulb
      state: "on"
  action:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.gyver_bulb
    - service: timer.cancel
      entity_id: timer.gyverlamp_1h_off

- id: Gyver_on_at_sleepingmode
  alias: Gyver_on_at_sleepingmode
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.virt_sleepingmode
    to: "on"
  action:
    # - service: light.turn_on
    #   data:
    #     brightness_pct: 5
    #     effect: Fire
    #   target:
    #     entity_id: light.gyver_bulb
    - service: mqtt.publish
      data_template:
        # topic: homeassistant/light/ESP-74e9c8/cmnd
        # payload: "P_ON"
        topic: homeassistant/light/ESP-74e9c8/switch
        payload: "ON"
    - delay:
        milliseconds: 500
    - service: mqtt.publish
      data_template:
        # topic: homeassistant/light/ESP-74e9c8/cmnd
        # payload: "EFF39"
        topic: homeassistant/light/ESP-74e9c8/effect/set
        payload: "Fire"

    - delay:
        milliseconds: 500
    - service: mqtt.publish
      data_template:
        # topic: homeassistant/light/ESP-74e9c8/cmnd
        # payload: "BRI20"
        topic: homeassistant/light/ESP-74e9c8/brightness/set
        payload: "20"
    - delay:
        milliseconds: 500
    - service: mqtt.publish
      data_template:
        # topic: homeassistant/light/ESP-74e9c8/cmnd
        # payload: "SPD255"
        topic: homeassistant/light/ESP-74e9c8/effect/speed/set
        payload: "1"

    - delay:
        milliseconds: 500
    - service: mqtt.publish
      data_template:
        # topic: homeassistant/light/ESP-74e9c8/cmnd
        # payload: "SCA1"
        topic: homeassistant/light/ESP-74e9c8/effect/scale/set
        payload: "1"
    - service: timer.start
      entity_id: timer.gyverlamp_1h_off
    # - service: mqtt.publish
    #   data_template:
    #     topic: homeassistant/light/ESP-74e9c8/cmnd
    #     payload: "TMR_SET 1 3 3600"
    # - delay:
    #     milliseconds: 500
    - delay:
        minutes: 60
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.gyver_lamp_esp_74e9c8
