#   Вмикаємо gyverlamp в редмиі "sleepingmode", і врубаємо таймер на годину (gyverlamp_1h_off)
- id: Gyver_on_at_sleepingmode
  alias: Gyver_on_at_sleepingmode
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.virt_sleepingmode
    to: "on"
  action:
    - service: select.select_option
      data:
        option: Fire 2012 # name of preset
      target:
        entity_id: select.wled_preset_2
    - service: timer.start
      entity_id: timer.gyverlamp_1h_off

#   Вимикаємо gyverlamp після спрацювання таймера на годину
- alias: Gyverlamp_off_1h_timer
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.gyverlamp_1h_off
  condition:
    - condition: state
      entity_id: light.gyver_lamp2
      state: "on"
  action:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.gyver_lamp2
    - service: timer.cancel
      entity_id: timer.gyverlamp_1h_off