#   Вмикаємо gyverlamp в редмиі "sleepingmode", і врубаємо таймер на годину (gyverlamp_1h_off)
- id: Gyver_on_at_sleepingmode
  alias: Gyver_on_at_sleepingmode
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.homemode
    to: "on"
  action:
    - service: light.turn_on
      data:
        brightness_pct: 1
        # effect: Fire 2012
        effect: Fire
      target:
        entity_id: light.gyver
    - service: timer.start
      entity_id: timer.gyverlamp_1h_off

#   Вимикаємо gyverlamp після спрацювання таймера на годину
- alias: Gyverlamp_off_1h_timer
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.gyverlamp_1h_off
  condition:
    - condition: state
      entity_id: light.gyver
      state: "on"
  action:
    - service: light.turn_off
      target:
        entity_id: light.gyver
    - service: timer.cancel
      entity_id: timer.gyverlamp_1h_off
