- alias: kitchenlight_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.kitchen_opple_action
      to: "button_3_single"
  action:
    - service: mqtt.publish
      data_template:
        topic: zigbee2mqtt_lan/Kitchen Color lamp/set
        payload: '{"state": "ON","transition": 1,"hue_power_on_behavior": "off","brightness": 254,"color_temp": 270}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: zigbee2mqtt_lan/Kitchen ceiling lamp/set
        payload: '{"state": "ON","transition": 1,"hue_power_on_behavior": "off","brightness": 254,"color_temp": 270}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: zigbee2mqtt_lan/Kitchen table lamp/set
        payload: '{"state": "ON","transition": 1,"hue_power_on_behavior": "off","brightness": 254,"color_temp": 270}'
        retain: true
- alias: kitchenlight_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.kitchen_opple_action
      to: "button_4_single"
  action:
    - service: mqtt.publish
      data_template:
        topic: zigbee2mqtt_lan/Kitchen Color lamp/set
        payload: '{"state": "OFF","transition": 1,"hue_power_on_behavior": "off"}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: zigbee2mqtt_lan/Kitchen ceiling lamp/set
        payload: '{"state": "OFF","transition": 1,"hue_power_on_behavior": "off"}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: zigbee2mqtt_lan/Kitchen table lamp/set
        payload: '{"state": "OFF","transition": 1,"hue_power_on_behavior": "off"}'
        retain: true
- alias: kitchenstripe_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.kitchen_opple_action
      to: "button_1_single"
  action:
    - service: mqtt.publish
      data_template:
        topic: zigbee2mqtt_lan/Kitchen strip/set
        payload: '{"state": "ON","brightness": 254,"color_temp": 270}'
        retain: true
- alias: kitchenstripe_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.kitchen_opple_action
      to: "button_2_single"
  action:
    - service: mqtt.publish
      data_template:
        topic: zigbee2mqtt_lan/Kitchen strip/set
        payload: '{"state": "OFF"}'
        retain: true
