- alias: guestroom_light_on_by_switch
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.guestroom_switch_action
      to: "button_1_single"
    - platform: state
      entity_id: sensor.guestroom_switch_action
      to: "button_2_single"
  action:
    - service: mqtt.publish
      data_template:
        topic: zigbee2mqtt_lan/Guestroom Color Bulb/set
        payload: '{"state": "ON","transition": 1,"hue_power_on_behavior": "recover","brightness": 254,"color_temp": 270}'
        retain: true

- alias: guestroom_light_off_by_switch
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.guestroom_switch_action
      to: "button_3_single"
    - platform: state
      entity_id: sensor.guestroom_switch_action
      to: "button_4_single"
  action:
    - service: mqtt.publish
      data_template:
        topic: zigbee2mqtt_lan/Guestroom Color Bulb/set
        payload: '{"state": "OFF","transition": 1,"hue_power_on_behavior": "recover"}'
        retain: true
