- alias: yardlightswitch_sleepingmode_on #освітлення в дворі вночі
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_motion_2
      to: "on"
  condition:
    - condition: state
      entity_id: switch.yard_light
      state: "off"
    - condition: state
      entity_id: sensor.home_mode
      state: "sleepingmode"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.yard_light
    - service: timer.start
      entity_id: timer.yardlightswitch_1m

# - alias: yardlightswitch_nightmode_on #освітлення в дворі ввечері
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.0x00158d000457e83c_occupancy
#       binary_sensor.front_door_motion_2
#       to: "on"
#   condition:
#     - condition: state
#       entity_id: switch.yard_light
#       state: "off"
#     - condition: state
#       entity_id: sensor.home_mode
#       state: "nightmode"
#   action:
#     - service: switch.turn_on
#       data:
#         entity_id: switch.yard_light
#     - service: timer.start
#       entity_id: timer.yardlightswitch_2m

- alias: yardlightswitch_on_manual
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0001644741_click
      to: "single"
    - platform: state
      entity_id: sensor.0x00158d0001644741_click
      to: "double"
  condition:
    - condition: state
      entity_id: switch.yard_light
      state: "off"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.yard_light
- alias: yardlightswitch_off_manual
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0001644741_click
      to: "single"
    - platform: state
      entity_id: sensor.0x00158d0001644741_click
      to: "double"
  condition:
    - condition: state
      entity_id: switch.yard_light
      state: "on"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.yard_light

- alias: yardlightswitch_off_timer_2m
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.yardlightswitch_2m
  condition:
    - condition: state
      entity_id: switch.yard_light
      state: "on"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.yard_light
    - service: timer.cancel
      entity_id: timer.yardlightswitch_2m

- alias: yardlightswitch_off_timer_1m
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.yardlightswitch_1m
  condition:
    - condition: state
      entity_id: switch.yard_light
      state: "on"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.yard_light
    - service: timer.cancel
      entity_id: timer.yardlightswitch_1m

- alias: yardlightswitch_timer_cancel
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.yard_light
      to: "off"
  action:
    - service: timer.cancel
      entity_id:
        - timer.yardlightswitch_2m
        - timer.yardlightswitch_1m
