- alias: telegram_outdoor_lights_status
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: "/light_outdoor"
  action:
    - service: telegram_bot.edit_message
      data_template:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.chat_id }}"
        title: '{{"\U0001F333"}} *Освітлення на вулиці*'
        message: >
          {%- if is_state("switch.outdoor_floodlight", "on") %}{{"\U0001F4A1"}}Deck floodlight is ON{{'\n'}}{% else %}Deck floodlight is ON{{'\n'}}{% endif -%}
          {%- if is_state("switch.yard_light", "on") %}{{"\U0001F4A1"}} Yard light is ON{{'\n'}}{% else %}Yard light is OFF{{'\n'}}{% endif -%}
          {%- if is_state("switch.backyard_light", "on") %}{{"\U0001F4A1"}} Backyard Light is ON{{'\n'}}{% else %}Backyard Light is OFF{{'\n'}}{% endif -%}
        inline_keyboard:
          - '{% if is_state("switch.outdoor_floodlight", "on") %}Deck floodlight OFF:/fdl_off{% else %}Deck floodlight ON:/fdl_on{% endif %}'
          - '{% if is_state("switch.yard_light", "on") %}Yard light OFF:/ydl_off{% else %}Yard light ON:/ydl_on{% endif %}'
          - '{% if is_state("switch.backyard_light", "on") %}Backyard Light Off:/bydl_off{% else %}Backyard Light ON:/bydl_on{% endif %}'
          - '{{ "\u21a9\ufe0f" }} Rooms and zones:/lights, {{ "\u21a9\ufe0f" }} Control Panel:/to_cp'

- alias: "IK - Telegram - Light outdoor fdl_off"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: "/fdl_off"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.outdoor_floodlight
    - delay: "00:00:02"
    - service: telegram_bot.edit_message
      data_template:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.chat_id }}"
        title: '{{"\U0001F333"}} *Освітлення на вулиці*'
        message: >
          {%- if is_state("switch.outdoor_floodlight", "on") %}{{"\U0001F4A1"}}Deck floodlight is ON{{'\n'}}{% else %}Deck floodlight is ON{{'\n'}}{% endif -%}
          {%- if is_state("switch.yard_light", "on") %}{{"\U0001F4A1"}} Yard light is ON{{'\n'}}{% else %}Yard light is OFF{{'\n'}}{% endif -%}
          {%- if is_state("switch.backyard_light", "on") %}{{"\U0001F4A1"}} Backyard Light is ON{{'\n'}}{% else %}Backyard Light is OFF{{'\n'}}{% endif -%}
        inline_keyboard:
          - '{% if is_state("switch.outdoor_floodlight", "on") %}Deck floodlight OFF:/fdl_off{% else %}Deck floodlight ON:/fdl_on{% endif %}'
          - '{% if is_state("switch.yard_light", "on") %}Yard light OFF:/ydl_off{% else %}Yard light ON:/ydl_on{% endif %}'
          - '{% if is_state("switch.backyard_light", "on") %}Backyard Light Off:/bydl_off{% else %}Backyard Light ON:/bydl_on{% endif %}'
          - '{{ "\u21a9\ufe0f" }} Rooms and zones:/lights, {{ "\u21a9\ufe0f" }} Control Panel:/to_cp'
- alias: "IK - Telegram - Light outdoor fdl_on"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: "/fdl_on"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.outdoor_floodlight
    - delay: "00:00:02"
    - service: telegram_bot.edit_message
      data_template:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.chat_id }}"
        title: '{{"\U0001F333"}} *Освітлення на вулиці*'
        message: >
          {%- if is_state("switch.outdoor_floodlight", "on") %}{{"\U0001F4A1"}}Deck floodlight is ON{{'\n'}}{% else %}Deck floodlight is ON{{'\n'}}{% endif -%}
          {%- if is_state("switch.yard_light", "on") %}{{"\U0001F4A1"}} Yard light is ON{{'\n'}}{% else %}Yard light is OFF{{'\n'}}{% endif -%}
          {%- if is_state("switch.backyard_light", "on") %}{{"\U0001F4A1"}} Backyard Light is ON{{'\n'}}{% else %}Backyard Light is OFF{{'\n'}}{% endif -%}
        inline_keyboard:
          - '{% if is_state("switch.outdoor_floodlight", "on") %}Deck floodlight OFF:/fdl_off{% else %}Deck floodlight ON:/fdl_on{% endif %}'
          - '{% if is_state("switch.yard_light", "on") %}Yard light OFF:/ydl_off{% else %}Yard light ON:/ydl_on{% endif %}'
          - '{% if is_state("switch.backyard_light", "on") %}Backyard Light Off:/bydl_off{% else %}Backyard Light ON:/bydl_on{% endif %}'
          - '{{ "\u21a9\ufe0f" }} Rooms and zones:/lights, {{ "\u21a9\ufe0f" }} Control Panel:/to_cp'

- alias: "IK - Telegram - Light outdoor ydl_off"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: "/ydl_off"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.yard_light
    - delay: "00:00:02"
    - service: telegram_bot.edit_message
      data_template:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.chat_id }}"
        title: '{{"\U0001F333"}} *Освітлення на вулиці*'
        message: >
          {%- if is_state("switch.outdoor_floodlight", "on") %}{{"\U0001F4A1"}}Deck floodlight is ON{{'\n'}}{% else %}Deck floodlight is ON{{'\n'}}{% endif -%}
          {%- if is_state("switch.yard_light", "on") %}{{"\U0001F4A1"}} Yard light is ON{{'\n'}}{% else %}Yard light is OFF{{'\n'}}{% endif -%}
          {%- if is_state("switch.backyard_light", "on") %}{{"\U0001F4A1"}} Backyard Light is ON{{'\n'}}{% else %}Backyard Light is OFF{{'\n'}}{% endif -%}
        inline_keyboard:
          - '{% if is_state("switch.outdoor_floodlight", "on") %}Deck floodlight OFF:/fdl_off{% else %}Deck floodlight ON:/fdl_on{% endif %}'
          - '{% if is_state("switch.yard_light", "on") %}Yard light OFF:/ydl_off{% else %}Yard light ON:/ydl_on{% endif %}'
          - '{% if is_state("switch.backyard_light", "on") %}Backyard Light Off:/bydl_off{% else %}Backyard Light ON:/bydl_on{% endif %}'
          - '{{ "\u21a9\ufe0f" }} Rooms and zones:/lights, {{ "\u21a9\ufe0f" }} Control Panel:/to_cp'
- alias: "IK - Telegram - Light outdoor ydl_on"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: "/ydl_on"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.yard_light
    - delay: "00:00:02"
    - service: telegram_bot.edit_message
      data_template:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.chat_id }}"
        title: '{{"\U0001F333"}} *Освітлення на вулиці*'
        message: >
          {%- if is_state("switch.outdoor_floodlight", "on") %}{{"\U0001F4A1"}}Deck floodlight is ON{{'\n'}}{% else %}Deck floodlight is ON{{'\n'}}{% endif -%}
          {%- if is_state("switch.yard_light", "on") %}{{"\U0001F4A1"}} Yard light is ON{{'\n'}}{% else %}Yard light is OFF{{'\n'}}{% endif -%}
          {%- if is_state("switch.backyard_light", "on") %}{{"\U0001F4A1"}} Backyard Light is ON{{'\n'}}{% else %}Backyard Light is OFF{{'\n'}}{% endif -%}
        inline_keyboard:
          - '{% if is_state("switch.outdoor_floodlight", "on") %}Deck floodlight OFF:/fdl_off{% else %}Deck floodlight ON:/fdl_on{% endif %}'
          - '{% if is_state("switch.yard_light", "on") %}Yard light OFF:/ydl_off{% else %}Yard light ON:/ydl_on{% endif %}'
          - '{% if is_state("switch.backyard_light", "on") %}Backyard Light Off:/bydl_off{% else %}Backyard Light ON:/bydl_on{% endif %}'
          - '{{ "\u21a9\ufe0f" }} Rooms and zones:/lights, {{ "\u21a9\ufe0f" }} Control Panel:/to_cp'

- alias: "IK - Telegram - Light outdoor bydl_off"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: "/bydl_off"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.backyard_light
    - delay: "00:00:02"
    - service: telegram_bot.edit_message
      data_template:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.chat_id }}"
        title: '{{"\U0001F333"}} *Освітлення на вулиці*'
        message: >
          {%- if is_state("switch.outdoor_floodlight", "on") %}{{"\U0001F4A1"}}Deck floodlight is ON{{'\n'}}{% else %}Deck floodlight is ON{{'\n'}}{% endif -%}
          {%- if is_state("switch.yard_light", "on") %}{{"\U0001F4A1"}} Yard light is ON{{'\n'}}{% else %}Yard light is OFF{{'\n'}}{% endif -%}
          {%- if is_state("switch.backyard_light", "on") %}{{"\U0001F4A1"}} Backyard Light is ON{{'\n'}}{% else %}Backyard Light is OFF{{'\n'}}{% endif -%}
        inline_keyboard:
          - '{% if is_state("switch.outdoor_floodlight", "on") %}Deck floodlight OFF:/fdl_off{% else %}Deck floodlight ON:/fdl_on{% endif %}'
          - '{% if is_state("switch.yard_light", "on") %}Yard light OFF:/ydl_off{% else %}Yard light ON:/ydl_on{% endif %}'
          - '{% if is_state("switch.backyard_light", "on") %}Backyard Light Off:/bydl_off{% else %}Backyard Light ON:/bydl_on{% endif %}'
          - '{{ "\u21a9\ufe0f" }} Rooms and zones:/lights, {{ "\u21a9\ufe0f" }} Control Panel:/to_cp'

- alias: "IK - Telegram - Light outdoor bydl_on"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: "/bydl_on"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.backyard_light
    - delay: "00:00:02"
    - service: telegram_bot.edit_message
      data_template:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.chat_id }}"
        title: '{{"\U0001F333"}} *Освітлення на вулиці*'
        message: >
          {%- if is_state("switch.outdoor_floodlight", "on") %}{{"\U0001F4A1"}}Deck floodlight is ON{{'\n'}}{% else %}Deck floodlight is ON{{'\n'}}{% endif -%}
          {%- if is_state("switch.yard_light", "on") %}{{"\U0001F4A1"}} Yard light is ON{{'\n'}}{% else %}Yard light is OFF{{'\n'}}{% endif -%}
          {%- if is_state("switch.backyard_light", "on") %}{{"\U0001F4A1"}} Backyard Light is ON{{'\n'}}{% else %}Backyard Light is OFF{{'\n'}}{% endif -%}
        inline_keyboard:
          - '{% if is_state("switch.outdoor_floodlight", "on") %}Deck floodlight OFF:/fdl_off{% else %}Deck floodlight ON:/fdl_on{% endif %}'
          - '{% if is_state("switch.yard_light", "on") %}Yard light OFF:/ydl_off{% else %}Yard light ON:/ydl_on{% endif %}'
          - '{% if is_state("switch.backyard_light", "on") %}Backyard Light Off:/bydl_off{% else %}Backyard Light ON:/bydl_on{% endif %}'
          - '{{ "\u21a9\ufe0f" }} Rooms and zones:/lights, {{ "\u21a9\ufe0f" }} Control Panel:/to_cp'
