- alias: shopinglist_updated
  initial_state: true
  trigger:
    - platform: event
      event_type: shopping_list_updated
      event_data:
        action: "add"
  action:
    - service: notify.telegram
      data:
        title: '{{"\U0001F4B5"}} *Shopping list*'
        message: "{{ trigger.event.data.item.name }} has been added to the shopping list"
        data:
          inline_keyboard:
            - '{{ "\u21a9\ufe0f" }} Control Panel:/to_cp'
