- platform: generic_thermostat
  name: Underfloor Heating Kitchen
  initial_hvac_mode: "heat"
  heater: switch.smart_plug_in_unit
  target_sensor: sensor.nspanel_temperature
  unique_id: uht_Kitchen
  target_temp_step: 1.0
  min_temp: 16
  max_temp: 28
  away_temp: 16
  home_temp: 22
