homeassistant: true
advanced:
  network_key:
    - 42
    - 219
    - 101
    - 83
    - 252
    - 68
    - 59
    - 94
    - 9
    - 154
    - 96
    - 207
    - 133
    - 116
    - 15
    - 180
  pan_id: 56186
  ext_pan_id:
    - 158
    - 127
    - 254
    - 18
    - 238
    - 170
    - 206
    - 113
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  last_seen: ISO_8601
  log_level: error
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: rohsha0feesh7Ooghuquee1phei4aichiSheiYu7wai8AhGieghooN5uR2phiiQu
serial:
  port: /dev/ttyUSB0
  adapter: ezsp
frontend:
  port: 8099
device_options:
  legacy: false
devices:
  '0xa4c138cc6a263fc3':
    friendly_name: inward
