esphome:
  name: led
  friendly_name: led
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
logger:
  level: NONE
api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
# captive_portal:
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO5
    num_leds: 18
    name: "NeoPixel Light"
    id: my_light
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          update_interval: 2s
      - addressable_rainbow:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - strobe:
          name: Police
          colors:
            - state: true
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 0ms
            - state: true
              red: 0%
              green: 0%
              blue: 100%
              duration: 500ms