substitutions:
  name: m5stack-atom-echo-889718
  friendly_name: M5Stack Atom Echo
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 0SQcngxIGgGHqhGR2ny/eIw2QcepnPziOFh3S7VUHB4=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
