esphome:
  name: mini-extreme
  friendly_name: mini extreme

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "1b880048dda2c209fb8da9c1dffc070d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mini-Extreme Fallback Hotspot"
    password: !secret ap_password

captive_portal:
    