- platform: tod
  name: Day_tod
  after: sunrise
  before: sunset

# - platform: template
#   sensors:
#     test_presence_fp1:
#       friendly_name: "test_presence fp1"
#       value_template: >
#         {{not is_state("sensor.0x54ef4410005832db_presence_event", "leave")}}
#       device_class: motion

