- platform: group
  name: Livingroom Lights
  entities:
    - light.livingroom_color_lamp_1
    - light.livingroom_color_lamp_2
    - light.livingroom_color_lamp_3

- platform: group
  name: Kitchen Ceiling Lights
  entities:
    - light.kitchen_table_lamp
    - light.kitchen_ceiling_lamp
    - light.kitchen_color_lamp
