- name: telegram
  platform: telegram
  chat_id: 66507631
- name: telegram_v
  platform: telegram
  chat_id: 1065413821
- name: telegram_yaroslava
  platform: telegram
  chat_id: 92494773
- platform: html5
  vapid_pub_key: !secret vapid_pub_key
  vapid_prv_key: !secret vapid_prv_key
  vapid_email: !secret vapid_email
