- name: telegram
  platform: telegram
  chat_id: !secret allowed_chat_id1
- name: telegram_v
  platform: telegram
  chat_id: !secret allowed_chat_id2
- name: telegram_yaroslava
  platform: telegram
  chat_id: !secret allowed_chat_id3
- platform: html5
  vapid_pub_key: !secret vapid_pub_key
  vapid_prv_key: !secret vapid_prv_key
  vapid_email: !secret vapid_email
