- platform: template
  switches:
    homemode:
      value_template: "{{ is_state('input_boolean.virt_sleepingmode', 'on') }}"
      friendly_name: "Sleep mode"
      unique_id: homemode
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.virt_sleepingmode
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.virt_sleepingmode
      icon_template: >-
        {% if is_state('input_boolean.virt_sleepingmode', 'on') %}
          mdi:chat-sleep-outline
        {% else %}
          mdi:chat-processing-outline
        {% endif %}

