substitutions:
  name: hallway_presence_sensor
  friendly_name: Hallway Presence Sensor
  projectname: "ceeed.ld2410"
  projecversion: "2.1"
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: Hallway
  project:
    name: ${projectname}
    version: ${projecversion}
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
logger:
  level: NONE
api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.10.15
    gateway: 192.168.10.1
    subnet: 255.255.255.0
esp32_improv:
  authorizer: none
# esp32_ble_tracker:
#   scan_parameters:
#     interval: 1100ms
#     window: 1100ms
#     active: true
bluetooth_proxy:
  active: true
uart:
  id: my_uart
  tx_pin: GPIO3
  rx_pin: GPIO5
  stop_bits: 1
  baud_rate: 256000
ld2410:
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
sensor:
  - platform: ld2410
    detection_distance:
      name: Detection Distance