substitutions:
  name: esp_player
  friendly_name: ESP player
  lrclk_mpin: GPIO5 #WS green
  bclk_mpin: GPIO7 #SCK yellow
  microphone_pin: GPIO6 #SD blue
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  min_version: 2023.10.1

esp32:
  board: esp32dev
  framework:
    type: esp-idf
external_components:
  - source: github://pr#5230
    components:
      - esp_adf
    refresh: 0s
esp_adf:
logger:
api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.10.108
    gateway: 192.168.10.1
    subnet: 255.255.255.0
button:
  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset

i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: ${lrclk_mpin}
    i2s_bclk_pin: ${bclk_mpin}

microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_audio_id: i2s_in
    i2s_din_pin: ${microphone_pin}
    adc_type: external
    pdm: false

voice_assistant:
  id: va
  microphone: echo_microphone
#   media_player: va_out
  noise_suppression_level: 3
  auto_gain: 31dBFS
  volume_multiplier: 8.0
  on_client_connected:
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - voice_assistant.start_continuous:
  on_client_disconnected:
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - voice_assistant.stop:
  on_wake_word_detected:
    - homeassistant.service:
        service: light.turn_on
        data:
          entity_id: light.voiceassistant_out_voice_led
          color_name: fuchsia
  on_listening: 
    - homeassistant.service:
        service: tts.cloud_say
        data:
          entity_id: media_player.voiceassistant_out_esphome_player
          message: Its me
    - delay: 4s
    - homeassistant.service:
        service: light.turn_off
        data:
          entity_id: light.voiceassistant_out_voice_led
  on_tts_start:
    - homeassistant.service:
        service: light.turn_on
        data:
          entity_id: light.voiceassistant_out_voice_led
          color_name: fuchsia
    - homeassistant.service:
        service: tts.cloud_say
        data:
          entity_id: media_player.voiceassistant_out_esphome_player
          message: !lambda 'return x;'
    - delay: 4s
    - homeassistant.service:
        service: light.turn_off
        data:
          entity_id: light.voiceassistant_out_voice_led


switch:
  - platform: template
    name: Use wake word
    id: use_wake_word
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    on_turn_on:
      - lambda: id(va).set_use_wake_word(true);
      - if:
          condition:
            not:
              - voice_assistant.is_running
          then:
            - voice_assistant.start_continuous
    on_turn_off:
      - voice_assistant.stop
      - lambda: id(va).set_use_wake_word(false);

